# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0003_auto_20161119_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationnote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
