# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RestFramework', '0010_auto_20161119_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationnote',
            name='user',
        ),
        migrations.AddField(
            model_name='locationnote',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
