# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0012_auto_20161120_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationnote',
            name='test',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
