# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0013_locationnote_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationnote',
            name='test',
        ),
    ]
