# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestFramework', '0016_auto_20161121_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='belongsTo',
        ),
        migrations.AddField(
            model_name='comment',
            name='belongsToID',
            field=models.IntegerField(default=-1),
        ),
    ]
